apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudshop-api
  namespace: cloudshop-app
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudshop-app
  selector:
    matchLabels:
      app: cloudshop-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
